#!/usr/bin/env python3
"""Convert JUnit XML reports into ci-issues.jsonl and a PR comment body.

Usage: ci-issues.py --check unit --junit reports/unit.xml [--junit ...] --out ci-issues.jsonl --comment comment.md

Each failure becomes one line: {"check","test_id","signature","message","paths"}.
The signature is sha256(check|test_id|first line of message)[:10] and matches the one
`.claude/hooks/issue.sh` derives when the title is "<test_id>: <first line>", so the Fable review can
compare the artifact against docs/00-context/KNOWN-ISSUES.md.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import xml.etree.ElementTree as ET


def first_line(s: str) -> str:
    return (s or "").strip().splitlines()[0][:200] if (s or "").strip() else ""


def paths_from(text: str) -> list[str]:
    return sorted(set(re.findall(r"(?:src|tests|schema)/[\w./-]+\.(?:py|sql|yaml|json|sh)", text or "")))


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", required=True)
    ap.add_argument("--junit", action="append", required=True)
    ap.add_argument("--out", default="ci-issues.jsonl")
    ap.add_argument("--comment", default="ci-issues-comment.md")
    a = ap.parse_args()

    issues = []
    for path in a.junit:
        try:
            root = ET.parse(path).getroot()
        except (ET.ParseError, OSError):
            continue
        for tc in root.iter("testcase"):
            for kind in ("failure", "error"):
                node = tc.find(kind)
                if node is None:
                    continue
                test_id = f"{tc.get('classname', '')}::{tc.get('name', '')}"
                msg = first_line(node.get("message") or node.text or kind)
                title = f"{test_id}: {msg}"
                sig = hashlib.sha256(f"{a.check}|{title}".encode()).hexdigest()[:10]
                issues.append({
                    "check": a.check, "test_id": test_id, "signature": sig, "message": msg,
                    "paths": paths_from((node.text or "") + " " + (tc.get("file") or "")),
                })

    with open(a.out, "w") as f:
        for i in issues:
            f.write(json.dumps(i) + "\n")

    with open(a.comment, "w") as f:
        if not issues:
            f.write(f"CI `{a.check}`: no failures.\n")
        else:
            f.write(f"## CI `{a.check}` failures ({len(issues)})\n\n")
            f.write("Record each one that is not yet in `docs/00-context/KNOWN-ISSUES.md`:\n\n")
            for i in issues:
                paths = ",".join(i["paths"])
                f.write(f"- `{i['signature']}` {i['test_id']} — {i['message']}\n")
                f.write(f"  `.claude/hooks/issue.sh --session <sid> \"{i['test_id']}: {i['message']}\" "
                        f"--check {a.check} --paths \"{paths}\"`\n")
            f.write("\n---\n_Generated by CI (examples/ci/ci-issues.py)_\n")
    print(f"{len(issues)} issue(s) written to {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
